services:
  task-list:
    build: .
    container_name: SimpleTaskList
    restart: unless-stopped
    ports:
      - "${PORT}:5000"
    volumes:
      # This mapping ensures your database survives if you delete the container
      - ./data:/app/data